### ISSUE TITLE
Display the game rules

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#10]
Right now, the game only displays *Rules Go Here* when a user starts the game and answers "yes" to the prompt: "would you like to see the rules?". Look into the code and the casino game of craps as it pertains to pass line betting and explain the rules to the user.

**Comment by NachoNav** [comment]
Done.  😃

**Comment by rfaile313** [comment]
Someone took care of this! Thank you! 🙏
