### ISSUE TITLE
"Animate" the dice! 

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#11]
This is an easy, but fun upgrade to the current project.

We want to give the user the illusion of dice rolling when they press a key to roll the dice: http://moziru.com/images/dice-clipart-animated-gif-13.gif

How to solve:
Look into ascii_dice.py. The dice are stored into an array. How could we iterate through the dice **randomly** while taking 1-2 seconds to do so before the user sees the result?

Hints: Use the random library already imported to randomly iterate through the different states of the array. `import time` to access the sleep() method. Roll your new process into a function.

**Comment by rfaile313** [comment]
I reverted this merge. I would like to keep the program without external dependencies to keep it newbie-friendly. Let's use the built-in random and time libraries to solve this problem instead of the asciimatics module.

**Comment by bx-r0** [comment]
Okay, no worries. I'll give it another go without the module

**Comment by rfaile313** [comment]
@AidanFray Thanks!

**Comment by JeremyBowyer** [comment]
@AidanFray are you still interested in taking a stab at this? If not, I could give it a try.

**Comment by bx-r0** [comment]
@JeremyBowyer I'm under a heavy workload atm so I haven't been able to have another go, but by all means, go ahead!

**Comment by rfaile313** [comment]
Someone took care of this! Thank you! 🙏
