### ISSUE TITLE
Remaining issues with odds math

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#12]
![screenshot_4](https://user-images.githubusercontent.com/13829168/33653410-ec8840ec-da21-11e7-9e2c-93d1c655d158.png)

**Comment by rfaile313** [comment]
![screenshot_5](https://user-images.githubusercontent.com/13829168/33653523-2ff282fc-da22-11e7-8cd1-ab2e5890bc1f.png)

**Comment by JeremyBowyer** [comment]
According to [the site you linked](http://www.crapsage.com/craps_payouts.php) in issue #5 it looks like 4 should payout 9:5, not 2:1. Or am I misunderstanding which odds are supposed to be used?

**Comment by JeremyBowyer** [comment]
On second look, there are multiple sections. Would this be for the "Place Bets" phase or the "Pass Line Odds/Come Bet Odds/Buy Bets" phase? I'm afraid I'm not too familiar with the rules and terminology for craps.

**Comment by rfaile313** [comment]
Hey @JeremyBowyer , I understand how that could be confusing. This program currently only supports pass line betting because there is no GUI for place or proposition betting. See attached.

![screenshot_7](https://user-images.githubusercontent.com/13829168/33708780-417c8daa-daf0-11e7-8052-95bfff7394db.png)

**Comment by JeremyBowyer** [comment]
@rfaile313 Makes sense. I'll update that and round the payout amounts to integers this evening.

**Comment by rfaile313** [comment]
This looks good @JeremyBowyer . Nice work. Closed.
