### ISSUE TITLE
Raise exception errors for non-acceptable input (i.e. trying to type a string for a bet.)

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#2]
For those looking to contribute to a project, this is a good start. This is an issue that needs fixing so that the program doesn't break upon receiving a string where an int should be. 

Where should you start if you choose to help try and fix this problem? Well, right here: https://docs.python.org/3/tutorial/errors.html !

**Comment by turbot151** [comment]
Hello, is this issue still open? I'd like to tackle this issue.

**Comment by rfaile313** [comment]
Absolutely! All issues are open to everyone. Make a pull and take a shot at it 😄

**Comment by rfaile313** [comment]
This issue has been resolved. Well done @turbot151 !
