### ISSUE TITLE
Better Control Flow

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#3]
The control flow for this program **is not good**. Purposely. How would you make it better? Does it even need to be in a class? Make a pull, mess around with it, and let's talk about it!

**Comment by rfaile313** [comment]
@AidanFray Did an excellent job of Improving it thus far with the addition of @Static Methods and a better main loop. Could it be even better? Take a shot.

**Comment by rfaile313** [comment]
Still looking for help on this :-)

**Comment by NachoNav** [comment]
Hey! I'm interested on this. Any suggestion or preference?

**Comment by rfaile313** [comment]
Hey! Nice! 

Not really. In my opinion it couldn't be worse than it already is. We can keep it in a Class but it probably doesn't need to be. 

Let's look at:
- Extrapolating the program where it makes sense -- i.e. we put ASCII DICE in another file, which is way better.
- Reducing the functions needed if possible, improving the functions.
- The overall control flow is... bad. We have the game running in a Class method that calls another class method, i.e.:
https://github.com/rfaile313/CrapsWithBettingSystem/blob/f8bffbbc3185fb931008b3432a84d6758aba49a6/main.py#L28

I'd be happy to work with you as you improve it 😄. Take a stab at it, make a PR, and let's look!

**Comment by NachoNav** [comment]
#22
