### ISSUE TITLE
Odds Math

### ISSUE THREAD

**Issue by rfaile313** [rfaile313/CrapsWithBettingSystem#5]
The odds math is incorrect for the casino game of table craps, and the values are returned to the bankroll incorrectly. 

Here's a link to how odds *should pay* on different numbers: http://www.crapsage.com/craps_payouts.php

Good issue for newcomers to programming, and/or programmers who enjoy math!

**Comment by bx-r0** [comment]
I'd like to work on this if no one else is?

**Comment by rfaile313** [comment]
Please do!

**Comment by rfaile313** [comment]
@JeremyBowyer this looks good! I didn't even catch the odds modifying the initial wager on line 122. Nice work. Merged.
